"""Presentation-only gettext-style catalogue. Machine identifiers stay unchanged.

English source messages are stable catalogue keys. A ContextVar scopes language
to a Streamlit script thread, avoiding cross-session global language state.
"""

from contextvars import ContextVar
from functools import partial
import re

DEFAULT_LANGUAGE = "tr"
LANGUAGES = {"tr": "Türkçe", "en": "English"}
_language = ContextVar("display_language", default=DEFAULT_LANGUAGE)

TR = {
    "PMSM engineering application": "PMSM Sürücü Devreye Alma Aracı",
    "Self-Commissioning PMSM Engineering": "PMSM Sürücü Devreye Alma Aracı",
    "release candidate": "sürüm adayı",
    "released": "yayımlandı",
    "Run Commissioning": "Devreye Almayı Başlat",
    "Drive / scenario configuration": "Sürücü ayarları",
    "M17 simulation preset": "M17 senaryosu",
    "Commissioning mode": "Devreye alma yöntemi",
    "Impairment exposure": "Hatanın uygulandığı aşama",
    "Deterministic seed": "Rastgelelik tohumu",
    "Known pole pairs [pairs]": "Kutup çifti sayısı",
    "Nominal DC bus [V]": "Nominal DC bara [V]",
    "Speed target [rpm]": "Hız hedefi [rpm]",
    "External operating load [N m]": "Yük torku [N m]",
    "Operating iq reference limit [A]": "iq referans sınırı [A]",
    "Dynamic deadline [s]": "Dinamik süre sınırı [s]",
    "Required dynamic hold [s]": "Hız bandında kalma süresi [s]",
    "Simulation evaluation / ground truth — plant configuration": "Gerçek motor parametreleri (simülasyon)",
    "Simulator inputs only. Estimators receive sampled records, not these constants.": "Yalnızca simülasyon için. Kestirici bu değerlere erişmez.",
    "Estimator-visible prior controller assumptions": "Başlangıç denetleyici parametreleri",
    "Commissioning excitation / noise / validation timing": "Uyartım ve ölçüm gürültüsü",
    "Simulation design constraints; no physical hardware-safety guarantee. Mechanical external load is explicitly zero.": "Mekanik kestirimde dış yük sıfırdır. Simülasyon sınırları donanım güvenliği garantisi değildir.",
    "Recorded electrical current noise SD [A]": "Akım gürültüsü σ [A]",
    "Recorded voltage noise SD [V]": "Gerilim gürültüsü σ [V]",
    "Driven-rotor commissioning speed [rpm]": "Akı kestirim hızı [rpm]",
    "Standstill voltage-program scale [dimensionless]": "Kilitli rotor uyartım ölçeği [1]",
    "Control-validation duration [s]": "Simülasyon süresi [s]",
    "Operating load-step time [s]": "Yük basamağı zamanı [s]",
    "Sampled-data commissioning / attempt history": "Kestirim aşamaları ve denemeler",
    "No estimator attempt completed. See the measurement/configuration failure below.": "Kestirim tamamlanmadı. Ölçüm veya yapılandırma hatasını inceleyin.",
    "Stage not fitted; downstream commissioning was blocked or measurement generation failed.": "Kestirim yapılmadı: önceki aşama reddedildi veya ölçüm alınamadı.",
    "Residual units: V s for electrical/flux stages; N m s for mechanical. Local sensitivities are not confidence probabilities.": "Model artığı: elektriksel/akı kestiriminde V s, mekanik kestirimde N m s. Yerel duyarlılık bir güven olasılığı değildir.",
    "Operating analysis — separate from commissioning quality": "Çalışma noktası analizi",
    "Unavailable: full commissioning rejected. No commissioned operation is fabricated.": "Devreye alma reddedildi; çalışma analizi yapılmadı.",
    "#### M14 steady operating feasibility": "#### Kararlı durum uygunluğu (M14)",
    "Steady analysis unavailable; see run warnings.": "Kararlı durum analizi yok. Uyarıları inceleyin.",
    "Existing classification: ": "Çalışma noktası: ",
    "#### M16 dynamic operating feasibility": "#### Dinamik uygunluk (M16)",
    "Dynamic analysis unavailable; see run warnings.": "Dinamik analiz yok. Uyarıları inceleyin.",
    "**Quasi-steady model estimate**": "**Yarı kararlı durum model kestirimi**",
    "Full dq transients can enter the band earlier. This quantity is not a universal physical lower bound.": "Tam dq geçici rejiminde hız bandına daha erken girilebilir. Bu kestirim fiziksel bir alt sınır değildir.",
    "**Controller-aware prediction on identified model**": "**Denetleyici modeliyle öngörü**",
    "Dynamic request / complete analysis / assumptions": "İstek, model varsayımları ve tanı bilgileri",
    "M16 predicts a constant load from t=0. Validation below applies the separately configured load step. Nominal bus/ideal sensing are M16 assumptions; configured M17 errors affect the hidden-plant validation separately.": "M16: t=0’dan itibaren sabit yük, nominal bara, ideal ölçüm. Doğrulama: seçilen yük basamağı ve M17 hataları.",
    "Closed-loop validation — Simulation evaluation / ground truth": "Kapalı çevrim doğrulama",
    "Evaluation-only information below is never used to accept commissioning or select retries.": "Gerçek simülasyon değerleri yalnızca değerlendirme içindir; kalite kararı veya yeniden deneme seçimi için kullanılmaz.",
    "No commissioned validation trace is available.": "Devreye alınmış denetleyici için doğrulama kaydı yok.",
    "Post-load metrics use existing M17/M15 definitions. iq tracking compares true currents to references mapped into the true frame. Recovery can be zero when the disturbance stays inside ±10 rpm; null means no finite recovery.": "M17/M15 yük sonrası ölçütleri. iq hatası gerçek dq eksen takımında hesaplanır. Hız ±10 rpm bandından çıkmazsa toparlanma süresi 0’dır; null, toparlanma bulunamadığını belirtir.",
    "Firmware configuration": "Firmware dışa aktarımı",
    "Portable firmware-ready control configuration — not deployed MCU firmware. No target timing, hardware validation or MISRA compliance is claimed.": "Taşınabilir C99 denetleyici yapılandırması. MCU’ya yükleme, donanım/zamanlama doğrulaması veya MISRA uygunluğu yoktur.",
    "Exported binary32 motor / current / speed constants": "Dışa aktarılan binary32 motor / akım / hız sabitleri",
    "Generate C header": "C Başlık Dosyası Oluştur",
    "Download C header": "C Başlık Dosyasını İndir",
    "Firmware export unavailable: full commissioning was rejected or the export configuration failed. Prior assumptions cannot be exported as commissioned estimates.": "Dışa aktarım kapalı: devreye alma reddedildi veya yapılandırma oluşturulamadı. Başlangıç parametreleri kestirim olarak dışa aktarılmaz.",
    "#### COMMITTED M18 VALIDATION EVIDENCE": "#### Kayıtlı Python/C doğrulaması (M18)",
    "Versioned evidence for the portable core; not a new parity test of this run. No compiler or replay executes on UI interaction.": "Depoya kayıtlı doğrulama; bu çalışmanın sonucu değildir. Arayüz derleyici veya yeniden oynatma çalıştırmaz.",
    "Artifact SHA-256: ": "Dosya SHA-256 değeri: ",
    "Full versioned parity record / compiler flags": "Doğrulama kaydı ve derleyici seçenekleri",
    "Strict > saturation flags can disagree at float32 rounding boundaries; all probes were retained.": "Float32 yuvarlama sınırında > karşılaştırması doyum durumunu farklı verebilir. Tüm sınır örnekleri kayıtta tutulmuştur.",
    "Results change only when Run Commissioning is submitted. Current inputs and last completed run may differ.": "Değişiklikler sonraki devreye almada uygulanır. Gösterilen sonuç son tamamlanan çalışmaya aittir.",
    "Generating sampled data, commissioning and evaluating accepted operation…": "Devreye alma ve doğrulama çalışıyor…",
    "Configure a simulation case and select Run Commissioning. Estimates and run metrics will be computed by the existing backend.": "Ayarları seçip Devreye Almayı Başlat düğmesine basın.",
    "Measurements → Rs/Ld/Lq → psi_f → J/B → gates/supervision → retuning → M14/M16 analysis → simulation validation → M18 export": "Ölçümler → Rs/Ld/Lq → psi_f → J/B → kalite kapıları/gözetim → yeniden ayarlama → M14/M16 analizi → simülasyon doğrulaması → M18 dışa aktarımı",
    "Reproducibility / estimator-visible configuration": "Çalışma kaydı ve kestirici girdileri",
    "Commissioning": "Devreye Alma",
    "Parameters / controllers": "Parametreler ve kontrol",
    "Operating analysis": "Çalışma noktası",
    "Simulation evaluation": "Doğrulama",
    "Nonidealities": "İdeal olmayan etkiler",
    "Firmware / M18": "Firmware ve tanı",
    "Prior → identified → active controller": "Motor parametreleri ve denetleyici kazançları",
    "Motor values and gains come from existing retuning/controller constructors. Rejection retains all prior controller parameters.": "Ret durumunda başlangıç denetleyici parametreleri korunur.",
    "M17 simulation stress/error models": "Ölçüm ve sürücü hata modeli (M17)",
    "Exposure controls commissioning, operation, or both; Rs drift applies only during operation. Nominal-bus FOC command and true terminal voltage are distinct; extra actual-bus clipping is not fed back into nominal anti-windup.": "Hatalar seçilen aşamaya uygulanır; Rs değişimi yalnızca çalışmada etkilidir. Komut ve motor uç gerilimi ayrıdır. Gerçek bara sınırlandırması nominal anti-windup’a geri beslenmez.",
    "#### Simulation evaluation / ground truth": "#### Gerçek simülasyon değerleri",
    "Measured/true current and commanded/terminal voltage curves are in the Simulation evaluation tab.": "Ölçülen/gerçek akımlar ve komut/uç gerilimleri Doğrulama sekmesindedir.",
    "Prepare run bundle": "Çalışma Paketini Hazırla",
    "Writing current-run JSON/CSV/plot/configuration bundle…": "Çalışma dosyaları hazırlanıyor…",
    "Download run bundle": "Çalışma Paketini İndir",
    "Machine-readable identifiers and JSON keys are preserved in both languages.": "Tanı kodları ve JSON alan adları sabittir.",
    "FULL ACCEPTED": "TAM KABUL",
    "REJECTED": "REDDEDİLDİ",
    "ACCEPT": "KABUL",
    "REJECT": "RET",
    "accepted": "kabul",
    "terminal": "sonlandırıldı",
    "one_shot": "Tek deneme",
    "adaptive": "Uyarlamalı gözetim",
    "combined": "Her iki aşama",
    "commissioning_only": "Yalnızca devreye alma",
    "operation_only": "Yalnızca çalışma",
    "standstill": "Kilitli rotor — Rs, Ld, Lq",
    "rotating": "Dönen rotor — psi_f",
    "mechanical": "Mekanik — J, B",
    "ideal": "Nominal (ideal)",
    "current_mild": "Akım ölçümü — hafif hata",
    "current_strong": "Akım ölçümü — yüksek hata",
    "voltage_mild": "Gerilim kestirimi — hafif hata",
    "voltage_strong": "Gerilim kestirimi — yüksek hata",
    "angle_mild": "Açı ofseti — küçük",
    "angle_strong": "Açı ofseti — büyük",
    "timing_one_sample": "Bir örneklik ölçüm gecikmesi",
    "inverter_mild": "İnverter gerilim hatası — küçük",
    "inverter_strong": "İnverter gerilim hatası — büyük",
    "bus_sag_mild": "DC bara gerilim düşümü — küçük",
    "bus_sag_strong": "DC bara gerilim düşümü — büyük",
    "rs_drift_mild": "Rs değişimi — hafif",
    "rs_drift_strong": "Rs değişimi — güçlü",
    "combined_mild": "Birleşik hatalar — hafif",
    "combined_strong": "Birleşik hatalar — yüksek",
    "Parameter": "Parametre",
    "Unit": "Birim",
    "Prior assumption": "Başlangıç varsayımı",
    "Identified / known": "Kestirilen / bilinen",
    "Controller value": "Denetleyici değeri",
    "Estimate": "Kestirilen değer",
    "Stage": "Aşama",
    "Attempt": "Deneme",
    "Quality": "Kalite",
    "Estimator succeeded": "Kestirim tamamlandı",
    "Reasons": "Nedenler",
    "Estimator failure": "Kestirici hatası",
    "Decision": "Karar",
    "Adaptive action": "Yeniden deneme adımı",
    "Next configuration": "Sonraki yapılandırma",
    "Loop": "Çevrim",
    "Constant": "Sabit",
    "Value": "Değer",
    "Current": "Akım",
    "Speed": "Hız",
    "Metric": "Ölçüt",
    "Quantity": "Büyüklük",
    "unavailable": "kullanılamıyor",
    "Check": "Kontrol",
    "Measured value": "Hesaplanan değer",
    "Limit": "Sınır",
    "Passed": "Sağlandı",
    "Post-hoc absolute error [%]": "Gerçek değere göre mutlak hata [%]",
    "Compiler": "Derleyici",
    "Compared input samples": "Karşılaştırılan giriş örnekleri",
    "Maximum absolute difference [V]": "En büyük mutlak fark [V]",
    "Maximum relative difference [ratio]": "En büyük bağıl fark [oran]",
    "Relative-worst signal": "Bağıl farkı en büyük sinyal",
    "Saturation agreement": "Doyum durumu uyumu",
    "Away-boundary agreement": "Yuvarlama sınırı dışında uyum",
    "Boundary disagreements": "Yuvarlama sınırındaki farklar",
    "feasible": "uygun",
    "voltage_limited": "gerilim sınırlı",
    "current_limited": "akım sınırlı",
    "evaluated": "değerlendirildi",
    "true": "Evet",
    "false": "Hayır",
    "Mechanical commissioning assumes explicitly known zero external load.": "Mekanik devreye alma, bilinen sıfır dış yük varsayar.",
    "M16 prediction uses constant load from t=0; closed-loop validation uses the configured load step.": "M16 öngörüsü t=0'dan itibaren sabit yük kullanır; kapalı çevrim doğrulama yapılandırılan yük basamağını kullanır.",
    "Rejected commissioning: prior parameters retained; commissioned operation and firmware export unavailable.": "Devreye alma reddedildi: başlangıç parametreleri korundu; devreye alınmış çalışma ve firmware dışa aktarımı kullanılamıyor.",
    "Configured M17 impairments are simulation stress/error models, not hardware specifications.": "M17 simülasyon hata modelleridir; donanım özelliklerini belirtmez.",
    "This run has good speed tracking but >10% post-hoc parameter error: speed tracking does not prove accurate commissioning.": "Hız izleme iyi, fakat gerçek değere göre parametre hatası %10’un üzerinde. İyi hız izleme, doğru parametre kestirimini kanıtlamaz.",
    "Simulated true speed": "Gerçek simülasyon hızı",
    "Reference": "Referans",
    "Speed [rpm]": "Hız [rpm]",
    "True id": "Gerçek id",
    "Measured id": "Ölçülen id",
    "d current [A]": "d akımı [A]",
    "True iq": "Gerçek iq",
    "Measured iq": "Ölçülen iq",
    "q current [A]": "q akımı [A]",
    "Reference mapped to true frame": "Gerçek dq ekseninde referans",
    "Controller-frame reference": "Denetleyici dq ekseninde referans",
    "True electromagnetic torque": "Gerçek elektromanyetik tork",
    "External load": "Dış yük",
    "Torque [N m]": "Tork [N m]",
    "Requested dq magnitude": "İstenen dq gerilim genliği",
    "Applied terminal magnitude": "Motor uç gerilim genliği",
    "Limited FOC command": "Sınırlanmış FOC komutu",
    "Nominal bus limit": "Nominal bara sınırı",
    "Actual bus limit": "Gerçek bara sınırı",
    "Voltage magnitude [V]": "Gerilim genliği [V]",
    "Nominal FOC saturation": "Nominal FOC doyumu",
    "Actual-bus clipping": "Gerçek bara sınırlandırması",
    "Saturation state [0/1]": "Doyum durumu [0/1]",
    "Simulation time [s]": "Simülasyon zamanı [s]",
    "Plots sampled for display; metrics use the full trace": "Grafikler gösterim için seyreltilmiştir; ölçütler tam kaydı kullanır",
    "Sample time [s]": "Örnek zamanı [s]",
    "Current [A]": "Akım [A]",
    "Measured speed [rad/s]": "Ölçülen hız [rad/s]",
    "No measurements": "Ölçüm yok",
    "No fitted model available": "Kestirilen model yok",
    "Observed back-EMF integral": "Gözlenen ters EMK integrali",
    "Fitted": "Model uyumu",
    "Window time [s]": "Pencere zamanı [s]",
    "Back-EMF integral [V s]": "Ters EMK integrali [V s]",
    "Reconstructed torque integral": "Akımlardan hesaplanan tork integrali",
    "Fitted J/B model": "Kestirilen J/B modeli",
    "Torque integral [N m s]": "Tork integrali [N m s]",
    "Prefix-fit time [s]": "Kullanılan veri süresi [s]",
    "Estimate / final estimate [dimensionless]": "Kestirilen değer / son kestirim [1]",
    "Prior controller retained.\nCommissioned operation and firmware export unavailable.": "Başlangıç denetleyicisi korundu.\nDevreye alınmış çalışma ve firmware dışa aktarımı kullanılamıyor.",
    "Control validation unavailable; accepted controller update retained.": "Denetim doğrulaması kullanılamıyor; kabul edilen denetleyici güncellemesi korundu.",
    "v{version} — {status}. Local simulation study; no hardware deployment.": "v{version} · {status} · Yerel simülasyon",
    "#### {stage} stage": "#### {stage}",
    "Attempt {number}: {status} — inspect measurements / diagnostics": "Deneme {number} · {status} · Ölçümler ve tanı",
    "Measurement provider failure (attempt {number}): {error}": "Ölçüm üretimi hatası (deneme {number}): {error}",
    "Committed parity evidence unavailable: {error}": "Depodaki eşdeğerlik kanıtı kullanılamıyor: {error}",
    "CURRENT RUN RESULTS: seed {seed} / {scenario} / {mode} / {exposure}": "Tohum {seed} · {mode} · {exposure}",
    "Current-run simulation evaluation / ground truth — {scenario}, seed {seed}": "Simülasyon doğrulaması — {scenario}, tohum {seed}",
    "Estimator-visible data — {stage}, attempt {number}": "Kestirim verileri — {stage}, deneme {number}",
    "control_iq_rmse_a": "Gerçek eksen takımında iq RMSE [A]",
    "max_speed_deviation_rpm": "En büyük hız sapması [rpm]",
    "recovery_time_s": "Toparlanma süresi [s]",
    "operation_status": "Çalışma değerlendirme durumu",
    "control_success": "Denetim başarısı",
    "true_id_rms_a": "Gerçek id RMS [A]",
    "controller_frame_iq_rmse_a": "Denetleyici eksen takımında iq RMSE [A]",
    "terminal_command_discrepancy_rmse_v": "Terminal/komut farkı RMSE [V]",
    "terminal_command_discrepancy_max_v": "En büyük terminal/komut farkı [V]",
    "nominal_bus_voltage_v": "Nominal bara gerilimi [V]",
    "actual_bus_voltage_v": "Gerçek bara gerilimi [V]",
    "final_speed_rpm": "Son hız [rpm]",
    "steady_state_feasible": "Kararlı durum uygun",
    "current_feasible": "Akım gereksinimi uygun",
    "voltage_feasible": "Gerilim gereksinimi uygun",
    "requested_speed_rpm": "İstenen hız [rpm]",
    "requested_load_torque_nm": "İstenen yük torku [N m]",
    "required_torque_nm": "Gerekli tork [N m]",
    "required_id_a": "Gerekli id [A]",
    "required_current_magnitude_a": "Gerekli akım genliği [A]",
    "current_margin_a": "Akım payı [A]",
    "current_utilization": "Akım kullanım oranı",
    "required_vd_v": "Gerekli vd [V]",
    "required_vq_v": "Gerekli vq [V]",
    "voltage_utilization": "Gerilim kullanım oranı",
    "electrical_speed_rad_s": "Elektriksel hız [rad/s]",
    "qualified_band_entry_time_s": "Kalma koşulunu sağlayan banda giriş [s]",
    "in_band_at_deadline": "Süre sınırında bandın içinde",
    "finite_signals": "Sinyaller sonlu",
    "current_reference_within_limit": "Akım referansı sınır içinde",
    "maximum_measured_current_a": "En büyük ölçülen akım [A]",
    "minimum_speed_rpm": "En düşük hız [rpm]",
    "maximum_voltage_utilization": "En büyük gerilim kullanım oranı",
    "saturation_fraction": "Doyum oranı",
    "effective_rank": "Etkin rank",
    "scaled_condition_number": "Ölçeklenmiş koşul sayısı",
    "noise_information_fraction": "Gürültü katkısı oranı",
    "split_relative_difference": "İki yarı veri kestiriminin bağıl farkı",
    "residual_rmse": "Model artığı RMSE",
    "relative_sensitivity": "Bağıl yerel duyarlılık",
    "component_snr": "Bileşen SNR",
    "control_speed_rmse_rpm": "Yük sonrası hız RMSE [rpm]",
    "control_iq_rmse_true_frame_a": "Gerçek eksen takımında iq RMSE [A]",
    "control_max_speed_deviation_rpm": "En büyük hız sapması [rpm]",
    "control_recovery_time_s": "Toparlanma süresi [s]",
    "command_saturation_fraction": "Komut doyum oranı",
    "actual_bus_saturation_fraction": "Gerçek bara doyum oranı",
    "true_current_peak_a": "En büyük gerçek akım [A]",
    "measured_current_peak_a": "En büyük ölçülen akım [A]",
    "command_voltage_utilization": "Komut gerilim kullanım oranı",
    "terminal_voltage_utilization": "Terminal gerilim kullanım oranı",
    "requested_rpm": "İstenen hız [rpm]",
    "load_torque_nm": "Yük torku [N m]",
    "required_iq_a": "Gerekli iq [A]",
    "required_voltage_magnitude_v": "Gerekli gerilim genliği [V]",
    "voltage_limit_v": "Gerilim sınırı [V]",
    "voltage_margin_v": "Gerilim payı [V]",
    "current_limit_a": "Akım sınırı [A]",
    "classification": "Sınıflandırma",
    "quasi_steady_transition_time_estimate_s": "Yarı kararlı durum geçiş süresi kestirimi [s]",
    "quasi_steady_completion_time_estimate_s": "Yarı kararlı durum tamamlanma süresi kestirimi [s]",
    "quasi_steady_deadline_met": "Yarı kararlı durum modelde süre sınırı sağlandı",
    "quasi_steady_band_reachable": "Yarı kararlı durum modelde banda erişilebilir",
    "predicted_closed_loop_success": "Öngörülen kapalı çevrim başarısı",
    "first_band_entry_time_s": "Banda ilk giriş zamanı [s]",
    "hold_completion_time_s": "Bantta kalma süresinin tamamlanması [s]",
    "reasons": "Nedenler",
    "kp_d": "Kp_d",
    "ki_d": "Ki_d",
    "kp_q": "Kp_q",
    "ki_q": "Ki_q",
    "kp": "Kp",
    "ki": "Ki",
    "anti_windup_gain": "Anti-windup kazancı",
    "torque_constant_nm_per_a": "Tork sabiti [N m/A]",
    "iq_limit_a": "iq sınırı [A]",
    "dc_bus_voltage_v": "DC bara gerilimi [V]",
    "pole_pairs": "Kutup çifti sayısı",
    "Motor parameters": "Motor parametreleri",
    "Commissioning setup": "Devreye alma ayarları",
    "Operating request": "Çalışma noktası",
    "Validation timing": "Doğrulama zamanlaması",
    "Simulation errors": "İdeal olmayan etkiler",
    "Identified parameters": "Kestirilen parametreler",
    "Estimates / prior retained": "Kestirimler / başlangıç korundu",
    "DC bus [V]": "DC bara [V]",
    "Steady-state feasibility": "Kararlı durum uygunluğu",
    "Dynamic feasibility": "Dinamik uygunluk",
    "Firmware export": "Firmware dışa aktarımı",
    "Available": "Kullanılabilir",
    "Blocked": "Engellendi",
    "Predicted success": "Başarı öngörülüyor",
    "Predicted failure": "Başarısızlık öngörülüyor",
    "Run summary": "Çalışma özeti",
    "Parameter identification": "Parametre kestirimi",
    "Operating point": "Çalışma noktası",
    "Steady-state": "Kararlı durum",
    "Residual": "Model artığı",
    "Excitation": "Uyartım",
    "Bias": "Bias / sistematik hata",
    "Voltage saturation": "Gerilim doyumu",
    "DC bus": "DC bara",
    "Quasi-steady": "Yarı kararlı durum",
    "Controller-aware prediction": "Denetleyici modeliyle öngörü",
    "Ground truth": "Gerçek simülasyon değerleri",
    "Retry": "Yeniden deneme",
    "Supervisor": "Gözetim",
    "Validation": "Doğrulama",
    "Diagnostics": "Tanı bilgileri",
    "Transient": "Geçici rejim",
}

EN = {
    "CURRENT RUN RESULTS: seed {seed} / {scenario} / {mode} / {exposure}": "Seed {seed} · {mode} · {exposure}",
    "ideal": "Nominal (ideal)",
    "one_shot": "One-shot",
    "adaptive": "Adaptive supervisor",
    "combined": "Both stages",
    "commissioning_only": "Commissioning only",
    "operation_only": "Operation only",
    "standstill": "Locked rotor — Rs, Ld, Lq",
    "rotating": "Rotating — psi_f",
    "mechanical": "Mechanical — J, B",
    "current_mild": "Current measurement — mild",
    "current_strong": "Current measurement — strong",
    "voltage_mild": "Voltage reconstruction — mild",
    "voltage_strong": "Voltage reconstruction — strong",
    "angle_mild": "Angle bias — mild",
    "angle_strong": "Angle bias — strong",
    "inverter_mild": "Inverter voltage error — mild",
    "inverter_strong": "Inverter voltage error — strong",
    "bus_sag_mild": "Bus sag — mild",
    "bus_sag_strong": "Bus sag — strong",
    "rs_drift_mild": "Rs drift — mild",
    "rs_drift_strong": "Rs drift — strong",
    "combined_mild": "Combined — mild",
    "combined_strong": "Combined — strong",
    "timing_one_sample": "Timing — one-sample delay",
    "PMSM engineering application": "PMSM Drive Commissioning Workbench",
    "Self-Commissioning PMSM Engineering": "PMSM Drive Commissioning Workbench",
    "Drive / scenario configuration": "Drive setup",
    "M17 simulation preset": "Error scenario (M17)",
    "Impairment exposure": "Apply errors during",
    "Known pole pairs [pairs]": "Pole pairs",
    "Deterministic seed": "Random seed",
    "External operating load [N m]": "Load torque [N m]",
    "Operating iq reference limit [A]": "iq reference limit [A]",
    "Required dynamic hold [s]": "In-band hold time [s]",
    "Simulation evaluation / ground truth — plant configuration": "True motor parameters (simulation)",
    "Simulator inputs only. Estimators receive sampled records, not these constants.": "Simulation only. Estimators do not receive these values.",
    "Estimator-visible prior controller assumptions": "Prior controller parameters",
    "Commissioning excitation / noise / validation timing": "Excitation and measurement noise",
    "Simulation design constraints; no physical hardware-safety guarantee. Mechanical external load is explicitly zero.": "Mechanical identification uses zero external load. Simulation limits are not hardware safety guarantees.",
    "Recorded electrical current noise SD [A]": "Current noise σ [A]",
    "Recorded voltage noise SD [V]": "Voltage noise σ [V]",
    "Driven-rotor commissioning speed [rpm]": "Flux identification speed [rpm]",
    "Standstill voltage-program scale [dimensionless]": "Locked-rotor excitation scale [1]",
    "Control-validation duration [s]": "Simulation duration [s]",
    "Operating load-step time [s]": "Load-step time [s]",
    "Sampled-data commissioning / attempt history": "Identification stages and attempts",
    "Stage not fitted; downstream commissioning was blocked or measurement generation failed.": "No fit: an earlier stage was rejected or measurements were unavailable.",
    "Operating analysis — separate from commissioning quality": "Operating point analysis",
    "Unavailable: full commissioning rejected. No commissioned operation is fabricated.": "Commissioning rejected; operating analysis unavailable.",
    "#### M14 steady operating feasibility": "#### Steady-state feasibility (M14)",
    "Existing classification: ": "Operating point: ",
    "#### M16 dynamic operating feasibility": "#### Dynamic feasibility (M16)",
    "**Controller-aware prediction on identified model**": "**Controller-aware prediction**",
    "Dynamic request / complete analysis / assumptions": "Request, model assumptions and diagnostics",
    "M16 predicts a constant load from t=0. Validation below applies the separately configured load step. Nominal bus/ideal sensing are M16 assumptions; configured M17 errors affect the hidden-plant validation separately.": "M16: constant load from t=0, nominal bus, ideal sensing. Validation: configured load step and M17 errors.",
    "Closed-loop validation — Simulation evaluation / ground truth": "Closed-loop validation",
    "Firmware configuration": "Firmware export",
    "Portable firmware-ready control configuration — not deployed MCU firmware. No target timing, hardware validation or MISRA compliance is claimed.": "Portable C99 control configuration. No MCU deployment, hardware/timing validation or MISRA compliance.",
    "#### COMMITTED M18 VALIDATION EVIDENCE": "#### Recorded Python/C validation (M18)",
    "Versioned evidence for the portable core; not a new parity test of this run. No compiler or replay executes on UI interaction.": "Committed validation evidence, not a result of this run. UI interactions do not compile or replay control samples.",
    "Full versioned parity record / compiler flags": "Validation record and compiler flags",
    "Results change only when Run Commissioning is submitted. Current inputs and last completed run may differ.": "Edits apply to the next commissioning run. Results show the last completed run.",
    "Generating sampled data, commissioning and evaluating accepted operation…": "Running commissioning and validation…",
    "Configure a simulation case and select Run Commissioning. Estimates and run metrics will be computed by the existing backend.": "Choose the drive settings, then select Run Commissioning.",
    "Reproducibility / estimator-visible configuration": "Run record and estimator inputs",
    "Parameters / controllers": "Parameters & control",
    "Operating analysis": "Operating point",
    "Simulation evaluation": "Validation",
    "Firmware / M18": "Firmware / diagnostics",
    "Prior → identified → active controller": "Motor parameters and controller gains",
    "Motor values and gains come from existing retuning/controller constructors. Rejection retains all prior controller parameters.": "Rejection retains the prior controller parameters.",
    "M17 simulation stress/error models": "Measurement and drive error model (M17)",
    "#### Simulation evaluation / ground truth": "#### Simulation ground truth",
    "Measured/true current and commanded/terminal voltage curves are in the Simulation evaluation tab.": "Measured/true currents and command/terminal voltages are plotted under Validation.",
    "Machine-readable identifiers and JSON keys are preserved in both languages.": "Diagnostic codes and JSON field names remain unchanged.",
    "v{version} — {status}. Local simulation study; no hardware deployment.": "v{version} · {status} · Local simulation",
    "#### {stage} stage": "#### {stage}",
    "Attempt {number}: {status} — inspect measurements / diagnostics": "Attempt {number} · {status} · Measurements and diagnostics",
    "Away-boundary agreement": "Agreement away from rounding boundaries",
    "Post-hoc absolute error [%]": "Absolute error against truth [%]",
    "control_speed_rmse_rpm": "Post-load speed RMSE [rpm]",
    "control_iq_rmse_true_frame_a": "True-frame iq RMSE [A]",
    "control_max_speed_deviation_rpm": "Maximum speed deviation [rpm]",
    "control_recovery_time_s": "Recovery time [s]",
    "control_iq_rmse_a": "True-frame iq RMSE [A]",
    "max_speed_deviation_rpm": "Maximum speed deviation [rpm]",
    "recovery_time_s": "Recovery time [s]",
    "command_saturation_fraction": "Command saturation fraction",
    "actual_bus_saturation_fraction": "Actual-bus saturation fraction",
    "true_current_peak_a": "Peak true current [A]",
    "measured_current_peak_a": "Peak measured current [A]",
    "command_voltage_utilization": "Command voltage utilization",
    "terminal_voltage_utilization": "Terminal voltage utilization",
    "required_iq_a": "Required iq [A]",
    "required_voltage_magnitude_v": "Required voltage magnitude [V]",
    "requested_rpm": "Requested speed [rpm]",
    "load_torque_nm": "Load torque [N m]",
    "current_limit_a": "Current limit [A]",
    "voltage_limit_v": "Voltage limit [V]",
    "voltage_margin_v": "Voltage margin [V]",
    "classification": "Classification",
    "quasi_steady_transition_time_estimate_s": "Quasi-steady transition estimate [s]",
    "quasi_steady_completion_time_estimate_s": "Quasi-steady completion estimate [s]",
    "quasi_steady_deadline_met": "Deadline met in quasi-steady model",
    "quasi_steady_band_reachable": "Band reachable in quasi-steady model",
    "predicted_closed_loop_success": "Predicted closed-loop success",
    "qualified_band_entry_time_s": "Qualified band entry [s]",
    "first_band_entry_time_s": "First band entry [s]",
    "hold_completion_time_s": "Hold completion [s]",
    "saturation_fraction": "Saturation fraction",
    "effective_rank": "Effective rank",
    "scaled_condition_number": "Scaled condition number",
    "noise_information_fraction": "Noise information fraction",
    "split_relative_difference": "Split-fit relative difference",
    "residual_rmse": "Residual RMSE",
    "relative_sensitivity": "Relative local sensitivity",
    "component_snr": "Component SNR",
}


def set_language(language):
    if language not in LANGUAGES:
        raise ValueError("unsupported_display_language")
    _language.set(language)


def translate(message, language, **values):
    """Unknown codes/messages survive verbatim; English is the source catalogue."""
    template = TR.get(message, message) if language == "tr" else EN.get(message, message)
    return template.format(**values) if values else template


def t(message, **values):
    return translate(message, _language.get(), **values)


def display_formatter():
    # Widget serialization can happen outside the script thread (e.g. AppTest).
    # Capture the selected language rather than consulting a different context.
    return partial(translate, language=_language.get())


def display_rows(rows):
    return [{t(key): t(value) if isinstance(value, str) else value for key, value in row.items()} for row in rows]


def localize_figure(figure):
    """Translate text artists only. No signal data, gains or estimator changes."""
    from matplotlib.text import Text
    patterns = (
        (r"Current-run simulation evaluation / ground truth — (.*), seed (\d+)\n(.*)",
         lambda m: t("Current-run simulation evaluation / ground truth — {scenario}, seed {seed}", scenario=t(m[1]), seed=m[2])+"\n"+t(m[3])),
        (r"Estimator-visible data — (.*), attempt (\d+)",
         lambda m: t("Estimator-visible data — {stage}, attempt {number}", stage=t(m[1]), number=m[2])),
    )
    for artist in figure.findobj(Text):
        text = artist.get_text()
        translated = t(text) if text in TR else "\n".join(t(line) for line in text.split("\n"))
        for pattern, render in patterns:
            match = re.fullmatch(pattern, text)
            if match:
                translated = render(match)
        artist.set_text(translated)
    return figure
